name: Continuous Integration

on:
  pull_request:
    branches: ["develop", "master"]
  push:
    branches: ["develop", "master"]

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - uses: Gr1N/setup-poetry@v4
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Run tests
        run: |
          poetry install
          poetry run tox -e py
      - name: Create code coverage report
        if: matrix.python_version == '3.7'
        run: poetry run pytest --cov=./
      - name: Upload code coverage report
        if: matrix.python_version == '3.7'
        uses: codecov/codecov-action@v1
